// <auto-generated />
using System;
using IgrejaCatalogo.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IgrejaCatalogo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240719022928_new")]
    partial class @new
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.6.24327.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IgrejaCatalogo.Models.Categoria", b =>
                {
                    b.Property<int>("CategoiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoiaId"));

                    b.Property<string>("CategoriaName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("CategoiaId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("IgrejaCatalogo.Models.Igreja", b =>
                {
                    b.Property<int>("IgrejaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IgrejaId"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("CategoiaId")
                        .HasColumnType("int");

                    b.Property<int?>("CodCategoriaCategoiaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateFundacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diocese")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ParocoResponsavel")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Telefone")
                        .HasColumnType("int");

                    b.HasKey("IgrejaId");

                    b.HasIndex("CodCategoriaCategoiaId");

                    b.ToTable("Igrejas");
                });

            modelBuilder.Entity("IgrejaCatalogo.Models.Igreja", b =>
                {
                    b.HasOne("IgrejaCatalogo.Models.Categoria", "CodCategoria")
                        .WithMany("Igrejas")
                        .HasForeignKey("CodCategoriaCategoiaId");

                    b.Navigation("CodCategoria");
                });

            modelBuilder.Entity("IgrejaCatalogo.Models.Categoria", b =>
                {
                    b.Navigation("Igrejas");
                });
#pragma warning restore 612, 618
        }
    }
}
